### ISSUE TITLE
Overwatch-js is completely broken

### ISSUE THREAD

**Issue by tlegoc** [gclem/overwatch-js#28]
My bot I was working on a long time ago dont work anymore.
I tried to fix it, but (as you can see), the api is returning slightly less data than before :

```
{ profile:
   { nick: 'Speedy',
     level: 31,
     avatar:
      'https://d15f34w2p8l1cc.cloudfront.net/overwatch/600a5cc024fa3daeca4eb397e5fcec66417a12ef47e2920dba1f835c25a7096c.png',
     rank: NaN,
     tier: '',
     platform: '',
     url: 'https://playoverwatch.com/en-us/career/pc/eu/Speedy-23165' },
  competitive:
   { global: { masteringHeroe: undefined },
     heroes: { competitive: {} } },
  quickplay:
   { global: { masteringHeroe: undefined },
     heroes: { quickplay: {} } },
  achievements: [] }
```

Any idea ?
Maybe should I use another api (sadly, because this is the best one), or maybe an update is required...
Thanks

**Comment by gclem** [comment]
Hi Edorion,

I will look closely on this tonight. I wondered if this one was used yet.

Honestly, I haven’t handle this lib since a long time. Apologies.

Sent from my phone. Please excuse any typo in this email.

________________________________
De : Edorion <notifications@github.com>
Envoyé : jeudi, décembre 27, 2018 1:58 PM
À : gclem/overwatch-js
Cc : Subscribed
Objet : [gclem/overwatch-js] Overwatch-js is completely broken (#28)


My bot I was working on a long time ago dont work anymore.
I tried to fix it, but (as you can see), the api is returning slightly less data than before :

{ profile:
   { nick: 'Speedy',
     level: 31,
     avatar:
      'https://d15f34w2p8l1cc.cloudfront.net/overwatch/600a5cc024fa3daeca4eb397e5fcec66417a12ef47e2920dba1f835c25a7096c.png',
     rank: NaN,
     tier: '',
     platform: '',
     url: 'https://playoverwatch.com/en-us/career/pc/eu/Speedy-23165' },
  competitive:
   { global: { masteringHeroe: undefined },
     heroes: { competitive: {} } },
  quickplay:
   { global: { masteringHeroe: undefined },
     heroes: { quickplay: {} } },
  achievements: [] }


Any idea ?
Maybe should I use another api (sadly, because this is the best one), or maybe an update is required...
Thanks

**Comment by tlegoc** [comment]
Actually the problem isn't from your api, it's just that I cant update overwatch-js using npm. 
I should have checked that before opening an issue, sorry to bother you...
Thanks
